name: Unit Testing
run-name: ${{ github.actor }} is testing the code
on: [push,pull_request,workflow_dispatch]
jobs: 
  run-tests:
    runs-on: linux
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup V
        uses: vlang/setup-v@1.3
      - name: Run Tests
        run: v test .
